name: build_docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          go run ./cmd/gen-docs/docs.go
          cp ./docs/fireql.md ./docs/index.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "docs update: latest" || echo "No document(s) updates found!"
          git push
          
